#!/usr/bin/env python
'''
Created on 19/01/2010

@author: peio
'''
import sys
from franklin.utils.cmd_utils import call

def run_blast():
    'It runs one of the blast+ programs'
    args = sys.argv[1:]
    stderr = None
    retcode = 0
    try:
        program_index = args.index('-p') + 1
        program = args[program_index]
        del args[program_index -1]
        del args[program_index -1 ]
    except IndexError:
        stderr = 'wrong parameters'
        retcode = 10
    cmd = [program]
    cmd.extend(args)
    # run the blast
    result, stderr, retcode = call(cmd, raise_on_error=False)
    sys.stdout.write(result)
    if stderr:
        sys.stderr.write(stderr)
    return retcode

if __name__ == '__main__':
     sys.exit(run_blast())
