#!/usr/bin/env python

# Copyright 2009 Jose Blanca, Peio Ziarsolo, COMAV-Univ. Politecnica Valencia
# This file is part of project.
# franklin is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# franklin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with franklin. If not, see <http://www.gnu.org/licenses/>.

'''
Created on 19/01/2010

@author: peio
'''
import sys
from franklin.utils.cmd_utils import call

def run_blast():
    'It runs one of the blast+ programs'
    args = sys.argv[1:]
    stderr = None
    retcode = 0
    try:
        program_index = args.index('-p') + 1
        program = args[program_index]
        del args[program_index -1]
        del args[program_index -1 ]
    except IndexError:
        stderr = 'wrong parameters'
        retcode = 10
    cmd = [program]
    cmd.extend(args)
    # run the blast
    result, stderr, retcode = call(cmd, raise_on_error=False)
    sys.stdout.write(result)
    if stderr:
        sys.stderr.write(stderr)
    return retcode

if __name__ == '__main__':
     sys.exit(run_blast())
